server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'neo4j-logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'neo4j'
          __path__: /logs/*.log  # Updated path to read logs from the mounted directory
