global:
  scrape_interval: 15s  # Set the scrape interval to 15 seconds

scrape_configs:
  - job_name: 'neo4j'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['neo4j-tdg:2004']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
